[project]
name = "lukefi.metsi.forestry"
description = "Models and functions for forestry computation."
version = "1.0.2"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Juho-Petteri Yliuntinen", email = "juho-petteri.yliuntinen@luke.fi"},
    { name = "Daniel Melander", email = "daniel.melander@luke.fi"},
    { name = "Arto Haara", email = "arto.haara@luke.fi"},
    { name = "Laura Jaakkola", email = "laura.jaakkola@luke.fi"},
    { name = "Tapio Lempinen"},
    { name = "Urho Niemelä"}
]
dependencies = [
    "scipy==1.7.3",
    "lupa==1.14.1",
    "lukefi.metsi.data @ https://github.com/lukefi/metsi-data/archive/refs/tags/1.0.0.zip",
    "fhk @ https://github.com/menu-hanke/fhk/releases/download/v4.0.0/fhk-4.0.0-cp310-cp310-win_amd64.whl ; platform_system=='Windows' and python_version=='3.10'",
    "fhk @ https://github.com/menu-hanke/fhk/releases/download/v4.0.0/fhk-4.0.0-cp311-cp311-win_amd64.whl ; platform_system=='Windows' and python_version=='3.11'",
    "fhk @ https://github.com/menu-hanke/fhk/releases/download/v4.0.0/fhk-4.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl ; platform_system=='Linux' and python_version=='3.10'",
    "fhk @ https://github.com/menu-hanke/fhk/releases/download/v4.0.0/fhk-4.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl ; platform_system=='Linux' and python_version=='3.11'"
]

[project.optional-dependencies]
tests = [
    "pytest",
    "parameterized == 0.8.1"
]
rpy = [
    "rpy2==3.5.2"
]

[tool.setuptools.package-data]
"lukefi.metsi.forestry.lua" = ["*"]
"lukefi.metsi.forestry.r" = ["*"]
